### ISSUE TITLE
Error: output for generator graphql-schema should be a .graphql-file

### ISSUE THREAD

**Issue by rfdc** [tylim88/Create-Prisma-App#3]
Great template, thanks a lot mate :) 

I ran into this error:
> ▸    Error: output for generator graphql-schema should be a .graphql-file. Please change the output property
>  ▸    for this generator in prisma.yml

-> Generator graphql-schema now outputs to a single file instead of a directory. That means you need to provide the full path including the file name to the generator. [#3359](https://github.com/prisma/prisma/issues/3359#issue-373441198)

So the variable `OUTPUT_FOLDER` inside the files at `.config` needs to be changed to the following: 
`OUTPUT_FOLDER=../src/prodSchema/prisma.graphql`

Hope that helps :)
cheers

**Comment by tylim88** [comment]
glad you found this template useful

regarding the error, seem like it is breaking change from prisma  v1.30 https://github.com/prisma/prisma/issues/3359#issuecomment-465934053

So I updated the template to v1.5.0 to fit the change https://github.com/tylim88/create-prisma-app/commit/210ca6f3afe1bb45f471d4b46ccb86b90af8c83e

Thank you for your help!
